# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gameProp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gameProp
  pod 'Toast-Swift', '~> 3.0.1'

  target 'gamePropTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gamePropUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
